### ISSUE TITLE
Allow drag-and-dropped files to populate the SwingFileWidget value

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava-ui-swing#14]
As requested by @imagejan in https://github.com/imagej/imagej-legacy/commit/55feddd337dc9f2342149669fdede9dd6e194501#commitcomment-11485193.

**Comment by imagejan** [comment]
[`fiji.util.gui.GenericDialogPlus`](https://github.com/fiji/fiji-lib/blob/b9277fa61648e4f4fad9c4524a551fbed99b4bdd/src/main/java/fiji/util/gui/GenericDialogPlus.java#L391-L405) implements drop targets for all text fields, including file fields. Maybe this can be done similarly for `SwingFileWidget` and `SwingTextWidget`.

**Comment by imagejan** [comment]
This is done in https://github.com/scijava/scijava-ui-swing/pull/27/commits/f0d2a878e5881ec4cf2c1de8f8484a7f0771c117 which is part of https://github.com/scijava/scijava-ui-swing/pull/27.
