### ISSUE TITLE
If cancelled, then the Look and Feel plugin dialog will not displayed again.

### ISSUE THREAD

**Issue by panovr** [scijava/scijava-ui-swing#23]
Choose `Edit`->`Options`->`Look and Feel...`, then the Look and Feel dialog will display.
However, if you hit the `Cancel` button, and run the Look and Feel plugin again, you will find that the Look and Feel dialog will not displayed again.

**Comment by ctrueden** [comment]
The Look & Feel dialog doesn't work very well in any case: it only controls Swing windows, whereas the ImageJ Legacy UI uses mostly AWT. It was originally written to support the new Swing UI, which almost no one uses anymore.

**Comment by ctrueden** [comment]
Fixed by scijava/scijava-common@1c1dfd663686f41a88342df6873ac861cf07a079.
