### ISSUE TITLE
Improve support for Look & Feels

### ISSUE THREAD

**Issue by ctrueden** [scijava/scijava-ui-swing#3]
The `OptionsLookAndFeel` lets you control the L&F for the active JVM. We need to improve it as follows:
- [ ] Persist the L&F setting.
- [ ] Create a LookAndFeelService that sets the initial L&F to match the persisted value.
- [ ] Add API to LookAndFeelService to change the L&F, including existing windows.

**Comment by tferr** [comment]
This is awesome! Just wanted to mention that from now on there setting L&F with FlatLaf should work on all the 3 supported OSes. With 2.4 there was an issue in which setting FlatLaf on MacOs would break AWT dialogs, but that is now fixed, and FlatLaf makes Fiji look great on MacOS too. Details: https://github.com/JFormDesigner/FlatLaf/issues/583
