### ISSUE TITLE
Sliders and scroll bars should scale to stepSize

### ISSUE THREAD

**Issue by imagejan** [scijava/scijava-ui-swing#31]
When using non-integer numeric inputs with `style="slider"` or `style="scroll bar"`, the UI widgets only support integer steps (because the underlying `JSlider` and `JScrollbar` objects only support `int` values).

This can be improved by scaling the slider range to the `[min; max]` range as follows:
* `slider.setMinimum(0)`
* `slider.setMaximum( (max-min) / stepSize )`
* `slider.setValue(  (value-min) / stepSize )`
* `value = slider.getValue() * stepSize + min`

and setting the slider/scrollbar labels to string representations of the scaled values.

**Comment by ctrueden** [comment]
Resolved by #35.
