### ISSUE TITLE
No parameter attribute for number formats

### ISSUE THREAD

**Issue by etadobson** [scijava/scijava-ui-swing#45]
This issue was recently [brought up on the forum](https://forum.image.sc/t/script-parameters-increasing-decimal-places-for-double/22919)... currently, if for example, you want to display the a default value of ```0.0178``` in the dialog for a user…

```#@Double(label="Distance", value=0.01780, persist=false) distance```

When the code runs… you get a pre-set value of ```0.018``` popping up and there is no current method to set the number of decimal places for that input.

As stated by @imagejan on the forum:

> "The spinner created in ```SwingNumberWidget``` is using the default ```DecimalFormat``` which apparently has a maximum of three decimal places.
> 
> You can somehow work around the issue by using a slider or scroll bar (within a defined range). But while the actual values can contain more decimal places (as shown by the ```println``` statement, there’s still no visual feedback inside the spinner text field:
> 
> ```#@ Double (label="Distance", min=0, max=0.05, value=0.01780, persist=false, stepSize=0.0001, style=slider) distance```
```println distance```
> 
> There’s no parameter attribute for number formats, but we could maybe use the `style` attribute for this; in any case we should try to guess a suitable spinner number format from the combination of min, max and stepSize, or from the default value…"

**Comment by BoudewijnvanLangerak** [comment]
Added code for formatting numerical values in the @Parameter annotation.
Code in the pullrequests:
https://github.com/scijava/scijava-common/pull/399
https://github.com/scijava/scijava-ui-swing/pull/50
