### ISSUE TITLE
NPE from SwingObjectWidget

### ISSUE THREAD

**Issue by karlduderstadt** [scijava/scijava-ui-swing#76]
The new Fiji release and update to pom 33.0.0 earlier this week bumped the version of scijava-ui-swing to 0.17.0. Surprisingly, and sadly, this change broke most of our groovy scripts. When running any script with a script parameter input asking for a MoleculeArchive, the main objects we work with in our software Mars, we get a NullPointerException:
<img width="1253" alt="Screenshot 2022-09-14 at 16 58 26" src="https://user-images.githubusercontent.com/17951396/190190728-faef5e53-33db-4af7-a5a0-e24f6c7c40dc.png">
This happens when I run the script with a MoleculeArchive already open:
```groovy
#@ MoleculeArchive archive

println(archive.getName())
```
and the dialog opens but is blank...
<img width="394" alt="Screenshot 2022-09-14 at 16 58 49" src="https://user-images.githubusercontent.com/17951396/190190786-ef3fe998-653d-4c9d-92e9-c8b24ca8d9cd.png">

This was even more exciting because our paper was published yesterday (https://elifesciences.org/articles/75899) and much of it depends on groovy scripts. So somehow after years of testing on the day of publication everything in all of our workflows was broken 😢 

I did test with the bundle before the release, but of course I somehow didn't test scripts... I narrowed the problem down to the changes in commit 7d36b386a2377835762632945350397d94bdf7af and in particular these lines now:
https://github.com/scijava/scijava-ui-swing/blob/5c32cba1a466d81d88f942adf1dfa1e9ee8dba6e/src/main/java/org/scijava/ui/swing/widget/SwingObjectWidget.java#L81-L86
this change was introduced between version 0.14.0 and 0.15.0

Somehow for our MoleculeArchives availableChoices is an empty list and then when getListCellRendererComponent is called the value is null and the NPE is thrown in the ObjectService when trying to getName...

The else part of the statement works perfectly because model.getObjectPool().toArray() returns a list with the archive and all is good.

However, I think availableChoices will never be null for DefaultMutableModuleItem since the empty list is created upon creation of that type of ModuleItem. So I would imagine this would be a problem for anyone trying to retrieve their particular Objects. Alternatively, maybe there is a mistake in our code or how we define our Objects, but I don't see it currently.

@imagejan do you have any insights here? I will keep investigating but I don't see how to fix the problem without removing this if else statement and leaving the else portion.

For now, the scijava framework came to the rescue. I created MarsSwingObjectWidget in mars-core in our project equivalent to version 0.14.0 with a higher priority to avoid the issue, but I would like to find a fix and remove that...

**Comment by ctrueden** [comment]
Oof, very sorry this happened. I'm working on fixing the breakages in the ImageJ macro language syntax highlighting and autocompletion, but will look into this also in the very near term.

**Comment by ctrueden** [comment]
@karlduderstadt I pushed one quick fix (cbc9ef6ca423e52cc40e052f560d25af054bc05c), with some defensive programming around the case where the value to be rendered is null. I don't know whether this gets the root of the bug (I don't know if the value *should* be null here...), but it should prevent the crash you are seeing. Feel free to give it a try by building scijava-ui-swing from source.

**Comment by karlduderstadt** [comment]
Will do, thanks a lot!

**Comment by karlduderstadt** [comment]
Thanks for the fast feedback. I don't get the NPE anymore, but the dialog comboBox has no choices anymore so this doesn't help much.
<img width="394" alt="Screenshot 2022-09-14 at 17 22 56" src="https://user-images.githubusercontent.com/17951396/190196639-5b206178-7006-47ac-a708-d53c32b577ae.png">

For now I pushed my copied version that overrides the problem to our update site yesterday. I am just still confused what is going on here.

**Comment by ctrueden** [comment]
@karlduderstadt When you have time: could you please test whether d40832c761c6d70527e5558928d5097b3fbf33d5 fixes your issue?

**Comment by karlduderstadt** [comment]
Yes @ctrueden that fixes the problem. I get list options again without any errors! 
<img width="394" alt="Screenshot 2022-09-14 at 21 14 12" src="https://user-images.githubusercontent.com/17951396/190242786-3f955bc8-9ffd-41e9-926f-350f2cb4b12d.png">

This does make me wonder why the choice list is empty in this case and whether there is something missing in my implementation...

In any case, thank you very much for the quick fix, I will close the issue and remember to test our scripts when you announce the next major update!
